### PR TITLE
chore(node-installer): bump to v0.17.0

### PR DESCRIPTION
**Pull request by vdice**
Bump the shim node-installer image to [v0.17.0](https://github.com/spinkube/containerd-shim-spin/releases/tag/v0.17.0)

### CODE REVIEW

**Comment by Mossaka** [comment]
Can Dependabot automate this?

**Review by Mossaka — APPROVED** [review]

**Comment by vdice** [comment]
> Can Dependabot automate this?

Good idea, will look into a follow-up.

**Comment by vdice** [comment]
> Can Dependabot automate this?

I experimented with the following [dependabot.yml on my fork](https://github.com/vdice/spinkube-azure/blob/main/.github/dependabot.yml) but it didn't seem to suggest any bumps.  Well, it makes sense for the node-installer image because we're already now at the latest v0.17.0 version, but I guess I was expecting that it would suggest updates to the cert-manager tags.  Yet the job appeared to be a no-op: https://github.com/vdice/spinkube-azure/actions/runs/11863326431/job/33064551328

Any ideas?

**Comment by Mossaka** [comment]
It seems like dependabot does not support helm chart dependencies: https://github.com/dependabot/dependabot-core/issues/2237

**Pull request merged**
